language: vim

env:
    global:
        - EnableNuGetPackageRestore=true

branches:
    only:
        - dev

git:
    submodules: false

before_script: |
    sudo apt-get update -qq > /dev/null
    sudo apt-get install -qq mono-devel > /dev/null
    mozroots --import --sync
    rm -rf ./server
    git clone https://github.com/junegunn/vader.vim
    git clone https://github.com/cd01/poshcomplete-server.git server
    xbuild ./server/PoshComplete/PoshComplete.csproj.ubuntu
    mono ./server/PoshComplete/bin/Debug/PoshComplete.exe 

script: |
    vim -Nu <(cat << VIMRC
    set rtp+=vader.vim
    set rtp+=.
    VIMRC) -c 'Vader! test/*' > /dev/null

after_script: |
    curl http://localhost:1234/stop

