language: objective-c

env:
    global:
        - EnableNuGetPackageRestore=true
    matrix:
        - MONO_VER="3.0.12"

branches:
    only:
        - dev

git:
    submodules: false

before_script: |
    wget "http://download.mono-project.com/archive/${MONO_VER}/macos-10-x86/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.dmg"
    hdid "MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.dmg"
    sudo installer -pkg "/Volumes/Mono Framework MDK ${MONO_VER}/MonoFramework-MDK-${MONO_VER}.macos10.xamarin.x86.pkg" -target /
    mozroots --import --sync
    rm -rf ./server
    git clone https://github.com/junegunn/vader.vim
    git clone https://github.com/cd01/poshcomplete-server.git server
    wget http://headsigned.com/download/running-nuget-command-line-on-linux/Microsoft.Build.zip -O server/Microsoft.Build.zip
    unzip ./server/Microsoft.Build.zip -d ./server
    wget http://nuget.org/nuget.exe -O ./server/nuget.exe
    mono ./server/nuget.exe restore ./server/PoshComplete.sln
    xbuild ./server/PoshComplete/PoshComplete.csproj.ubuntu
    mono ./server/PoshComplete/bin/Debug/PoshComplete.exe 

script: |
    vim -Nu <(cat << VIMRC
    set rtp+=vader.vim
    set rtp+=.
    VIMRC) -c 'Vader! test/*' > /dev/null

after_script: |
    curl http://localhost:1234/stop

